In [2]:
import tensorflow as tf
from tensorflow import keras
from keras.utils import image_dataset_from_directory
from keras.applications.mobilenet_v2 import MobileNetV2, preprocess_input, decode_predictions
from keras.models import Sequential
from keras.layers import Dense, GlobalAveragePooling2D, Dropout

In [3]:
# Loading training and validation data 
train_data = image_dataset_from_directory(
    directory="../data/raw/train/images",
    label_mode = 'categorical',
    color_mode='rgb',
    image_size=(200, 200),
    batch_size=32
)

test_data = image_dataset_from_directory(
    directory="../data/raw/validation/images",
    label_mode = 'categorical',
    color_mode='rgb',
    image_size=(200, 200),
    batch_size=32,
    shuffle=False
)

Found 1440 files belonging to 6 classes.
Found 360 files belonging to 6 classes.


In [4]:
# NORMALIZING THE IMAGES

def preprocess(image, label):
    image = tf.image.resize(image, (224, 224))
    image = preprocess_input(image)
    return image, label

train_input = train_data.map(preprocess)
test_input = test_data.map(preprocess)

In [5]:
AUTOTUNE = tf.data.AUTOTUNE

train_input = train_input.cache().prefetch(buffer_size=AUTOTUNE)
test_input = test_input.prefetch(tf.data.AUTOTUNE)

In [6]:
# Data Augmentation
augment_step = Sequential([
    tf.keras.layers.RandomFlip("horizontal"),
    tf.keras.layers.RandomRotation(0.05),
    tf.keras.layers.RandomZoom(0.1)
])

In [7]:
# Using MobileNetV2 model 
base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(224, 224,3))

In [8]:
print(len(base_model.layers))

154


In [9]:
# Freezing all layers of the base model, except top 25 layers and re-training the weights
base_model.trainable = True

for base_layer in base_model.layers[:-30]:
    base_layer.trainable = False

In [10]:
model = Sequential()

model.add(keras.layers.Input(shape=(224, 224,3)))

model.add(augment_step)

model.add(base_model)

model.add(GlobalAveragePooling2D())

model.add(Dense(128,activation='relu'))
model.add(Dropout(0.3))

model.add(Dense(6, activation='softmax'))

In [11]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ sequential (Sequential)         │ (None, 224, 224, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ mobilenetv2_1.00_224            │ (None, 7, 7, 1280)     │     2,257,984 │
│ (Functional)                    │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling2d        │ (None, 1280)           │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │       163,968 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 6)              │           774 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,422,726 (9.24 MB)

 Trainable params: 1,691,142 (6.45 MB)

 Non-trainable params: 731,584 (2.79 MB)

In [12]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5), loss='categorical_crossentropy', metrics = ['accuracy'])

In [13]:
history = model.fit(train_input, epochs=20, validation_data=test_input)

Epoch 1/20


45/45 ━━━━━━━━━━━━━━━━━━━━ 84s 1s/step - accuracy: 0.4375 - loss: 1.4729 - val_accuracy: 0.5000 - val_loss: 1.5111
Epoch 2/20
45/45 ━━━━━━━━━━━━━━━━━━━━ 54s 1s/step - accuracy: 0.7688 - loss: 0.8688 - val_accuracy: 0.5639 - val_loss: 1.3134
Epoch 3/20
45/45 ━━━━━━━━━━━━━━━━━━━━ 54s 1s/step - accuracy: 0.9118 - loss: 0.5443 - val_accuracy: 0.5917 - val_loss: 1.1826
Epoch 4/20
45/45 ━━━━━━━━━━━━━━━━━━━━ 77s 1s/step - accuracy: 0.9354 - loss: 0.3819 - val_accuracy: 0.6500 - val_loss: 1.0489
Epoch 5/20
45/45 ━━━━━━━━━━━━━━━━━━━━ 50s 1s/step - accuracy: 0.9563 - loss: 0.2797 - val_accuracy: 0.6722 - val_loss: 0.9536
Epoch 6/20
45/45 ━━━━━━━━━━━━━━━━━━━━ 48s 1s/step - accuracy: 0.9771 - loss: 0.1994 - val_accuracy: 0.7306 - val_loss: 0.8423
Epoch 7/20
45/45 ━━━━━━━━━━━━━━━━━━━━ 47s 1s/step - accuracy: 0.9771 - loss: 0.1602 - val_accuracy: 0.7639 - val_loss: 0.7627
Epoch 8/20
45/45 ━━━━━━━━━━━━━━━━━━━━ 47s 1s/step - accuracy: 0.9812 - loss: 0.1298 - val_accuracy: 0.7833 - val_loss: 0.6876
Epo

In [14]:
# Analyzing errors

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report

y_true = []
y_pred = []

for images, labels in test_input:
    pred = model.predict(images)

    y_true.extend(np.argmax(labels.numpy(), axis = 1))
    y_pred.extend(np.argmax(pred, axis = 1))

y_true = np.array(y_true)
y_pred = np.array(y_pred)



1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 628ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 616ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 673ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 639ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 620ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 630ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 641ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 619ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 620ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 657ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step


In [15]:
print(confusion_matrix(y_true, y_pred))

[[60  0  0  0  0  0]
 [ 0 60  0  0  0  0]
 [ 1  0 59  0  0  0]
 [ 6  2  0 51  1  0]
 [ 0  0  0  0 60  0]
 [ 0  0  0  0  7 53]]


In [16]:
class_names = train_data.class_names
print(class_names)

print(classification_report(y_true, y_pred, target_names=class_names))



['crazing', 'inclusion', 'patches', 'pitted_surface', 'rolled-in_scale', 'scratches']
                 precision    recall  f1-score   support

        crazing       0.90      1.00      0.94        60
      inclusion       0.97      1.00      0.98        60
        patches       1.00      0.98      0.99        60
 pitted_surface       1.00      0.85      0.92        60
rolled-in_scale       0.88      1.00      0.94        60
      scratches       1.00      0.88      0.94        60

       accuracy                           0.95       360
      macro avg       0.96      0.95      0.95       360
   weighted avg       0.96      0.95      0.95       360



In [ ]:
#Saving the model

model.save("../models/surface_detection_model.keras")

In [19]:
#Saving class names as json file
import json

class_names = train_data.class_names

with open("../models/class_names.json", "w") as f:
    json.dump(class_names, f)
