In [112]:
import tensorflow as tf
from tensorflow import keras
from keras.utils import image_dataset_from_directory
from keras.preprocessing import image
from keras.applications.mobilenet_v2 import MobileNetV2, preprocess_input, decode_predictions
from keras.models import Sequential
from keras.layers import Dense, Conv2D, GlobalAveragePooling2D, BatchNormalization, Dropout, Flatten

In [125]:
# Loading training and validation data 
train_data = image_dataset_from_directory(
    directory="../data/raw/train/images",
    label_mode = 'categorical',
    color_mode='rgb',
    image_size=(200, 200),
    batch_size=32
)

test_data = image_dataset_from_directory(
    directory="../data/raw/validation/images",
    label_mode = 'categorical',
    color_mode='rgb',
    image_size=(200, 200),
    batch_size=32,
    shuffle=False
)

Found 1440 files belonging to 6 classes.
Found 360 files belonging to 6 classes.


In [128]:
# NORMALIZING THE IMAGES

def preprocess(image, label):
    image = tf.image.resize(image, (224, 224))
    image = preprocess_input(image)
    return image, label

train_input = train_data.map(preprocess)
test_input = test_data.map(preprocess)

In [129]:
AUTOTUNE = tf.data.AUTOTUNE

train_input = train_input.cache().prefetch(buffer_size=AUTOTUNE)
test_input = test_input.prefetch(tf.data.AUTOTUNE)

In [130]:
# Data Augmentation
augment_step = Sequential([
    tf.keras.layers.RandomFlip("horizontal"),
    tf.keras.layers.RandomRotation(0.05),
    tf.keras.layers.RandomZoom(0.1)
])

In [131]:
base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(224, 224,3))

In [132]:
print(len(base_model.layers))

154


In [133]:
# Freezing all layers of the base model, except top 25 layers and re-training the weights
base_model.trainable = True

for base_layer in base_model.layers[:-30]:
    base_layer.trainable = False

In [134]:
model = Sequential()

model.add(keras.layers.Input(shape=(224, 224,3)))

model.add(augment_step)

model.add(base_model)

model.add(GlobalAveragePooling2D())

model.add(Dense(128,activation='relu'))
model.add(Dropout(0.3))

model.add(Dense(6, activation='softmax'))

In [135]:
model.summary()

Model: "sequential_17"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ sequential_16 (Sequential)      │ (None, 224, 224, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ mobilenetv2_1.00_224            │ (None, 7, 7, 1280)     │     2,257,984 │
│ (Functional)                    │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling2d_7      │ (None, 1280)           │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 128)            │       163,968 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 6)              │           774 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,422,726 (9.24 MB)

 Trainable params: 1,691,142 (6.45 MB)

 Non-trainable params: 731,584 (2.79 MB)

In [136]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5), loss='categorical_crossentropy', metrics = ['accuracy'])

In [143]:
history = model.fit(train_input, epochs=15, validation_data=test_input)

Epoch 1/15
45/45 ━━━━━━━━━━━━━━━━━━━━ 52s 1s/step - accuracy: 0.9757 - loss: 0.1867 - val_accuracy: 0.6750 - val_loss: 0.9761
Epoch 2/15
45/45 ━━━━━━━━━━━━━━━━━━━━ 49s 1s/step - accuracy: 0.9750 - loss: 0.1576 - val_accuracy: 0.7056 - val_loss: 0.8766
Epoch 3/15
45/45 ━━━━━━━━━━━━━━━━━━━━ 49s 1s/step - accuracy: 0.9840 - loss: 0.1220 - val_accuracy: 0.7389 - val_loss: 0.7803
Epoch 4/15
45/45 ━━━━━━━━━━━━━━━━━━━━ 49s 1s/step - accuracy: 0.9854 - loss: 0.0992 - val_accuracy: 0.7611 - val_loss: 0.6970
Epoch 5/15
45/45 ━━━━━━━━━━━━━━━━━━━━ 49s 1s/step - accuracy: 0.9847 - loss: 0.0897 - val_accuracy: 0.7694 - val_loss: 0.6284
Epoch 6/15
45/45 ━━━━━━━━━━━━━━━━━━━━ 48s 1s/step - accuracy: 0.9875 - loss: 0.0809 - val_accuracy: 0.8000 - val_loss: 0.5594
Epoch 7/15
45/45 ━━━━━━━━━━━━━━━━━━━━ 49s 1s/step - accuracy: 0.9917 - loss: 0.0644 - val_accuracy: 0.8250 - val_loss: 0.5037
Epoch 8/15
45/45 ━━━━━━━━━━━━━━━━━━━━ 72s 2s/step - accuracy: 0.9896 - loss: 0.0599 - val_accuracy: 0.8444 - val_loss:

In [144]:
# Analyzing errors

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report

y_true = []
y_pred = []

for images, labels in test_input:
    pred = model.predict(images)

    y_true.extend(np.argmax(labels.numpy(), axis = 1))
    y_pred.extend(np.argmax(pred, axis = 1))

y_true = np.array(y_true)
y_pred = np.array(y_pred)



1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 858ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 774ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 750ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 779ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 747ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 670ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 682ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 661ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 657ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 856ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 871ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 279ms/step


In [145]:
print(confusion_matrix(y_true, y_pred))

[[60  0  0  0  0  0]
 [ 0 60  0  0  0  0]
 [ 3  2 53  0  2  0]
 [ 7  1  0 49  3  0]
 [ 0  0  0  0 60  0]
 [ 0  0  0  0  7 53]]


In [146]:
class_names = train_data.class_names
print(class_names)

print(classification_report(y_true, y_pred, target_names=class_names))



['crazing', 'inclusion', 'patches', 'pitted_surface', 'rolled-in_scale', 'scratches']
                 precision    recall  f1-score   support

        crazing       0.86      1.00      0.92        60
      inclusion       0.95      1.00      0.98        60
        patches       1.00      0.88      0.94        60
 pitted_surface       1.00      0.82      0.90        60
rolled-in_scale       0.83      1.00      0.91        60
      scratches       1.00      0.88      0.94        60

       accuracy                           0.93       360
      macro avg       0.94      0.93      0.93       360
   weighted avg       0.94      0.93      0.93       360

